### ISSUE TITLE
Crash on "Solaar Show"

### ISSUE THREAD

**Issue by GarThor** [pwr-Solaar/Solaar#3098]
This is a known bug.  See several comments below for a new bug.

- Solaar version (`solaar --version` or `git describe --tags` if cloned from this repository):
```
> solaar --version
rules cannot access modifier keys in Wayland, accessing process only works on GNOME with Solaar Gnome extension installed
solaar 1.1.18+202512130008
```
- Distribution: 
```
Ubuntu 25.10
```
- Kernel version (ex. `uname -srmo`):
```
> uname -srmo
Linux 6.17.0-8-generic x86_64 GNU/Linux
``` 
- Output of `solaar show`:
```
solaar show
rules cannot access modifier keys in Wayland, accessing process only works on GNOME with Solaar Gnome extension installed
solaar version 1.1.18+202512130008


G432 Gaming Headset
     Device path  : /dev/hidraw5
     USB id       : 046d:0A9C
     Codename     : G432
     Kind         : ?
     Protocol     : HID++ 4.2
     Serial number: 
     Model ID:      000000000A9C
     Unit ID:       FFFFFFFF
                 0: U1  42.00.B0001
solaar: error: Traceback (most recent call last):
  File "/usr/share/solaar/lib/solaar/cli/__init__.py", line 216, in run
    m.run(c, args, _find_receiver, _find_device)
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/solaar/lib/solaar/cli/show.py", line 336, in run
    _print_device(d)
    ~~~~~~~~~~~~~^^^
  File "/usr/share/solaar/lib/solaar/cli/show.py", line 131, in _print_device
    notification_flags = _hidpp10.get_notification_flags(dev)
  File "/usr/share/solaar/lib/logitech_receiver/hidpp10.py", line 192, in get_notification_flags
    return NotificationFlag(self._get_register(device, Registers.NOTIFICATIONS))
  File "/usr/lib/python3.13/enum.py", line 726, in __call__
    return cls.__new__(cls, value)
           ~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/lib/python3.13/enum.py", line 1211, in __new__
    raise exc
  File "/usr/lib/python3.13/enum.py", line 1188, in __new__
    result = cls._missing_(value)
  File "/usr/lib/python3.13/enum.py", line 1467, in _missing_
    raise ValueError(
            "%r is not a valid %s" % (value, cls.__qualname__)
            )
ValueError: None is not a valid NotificationFlag
```

- Contents of `~/.config/solaar/config.yaml` (or `~/.config/solaar/config.json` if `~/.config/solaar/config.yaml` not present):

<details>

```
cat ~/.config/solaar/config.yaml 
- 1.1.16-21-gdbc97d96
- _NAME: MX Vertical Wireless Mouse
  _modelId: B020407BC08A
  _sensitive: {divert-keys: true, dpi: true, lowres-scroll-mode: false, persistent-remappable-keys: false, reprogrammable-keys: false}
  _unitId: 30E43C76
  change-host: null
  divert-keys: {82: 0, 83: 0, 86: 0, 253: 2}
  dpi: 3600
  lowres-scroll-mode: false
  persistent-remappable-keys: null
  reprogrammable-keys: {80: 80, 81: 81, 82: 82, 83: 83, 86: 86, 253: 253}
- _NAME: G432 Gaming Headset
  _absent: [hi-res-scroll, lowres-scroll-mode, hires-smooth-invert, hires-smooth-resolution, hires-scroll-mode, scroll-ratchet, scroll-ratchet-torque, smart-shift,
    thumb-scroll-invert, thumb-scroll-mode, onboard_profiles, report_rate, report_rate_extended, pointer_speed, dpi, dpi_extended, speed-change, backlight,
    backlight_level, backlight_duration_hands_out, backlight_duration_hands_in, backlight_duration_powered, backlight-timed, led_control, led_zone_, rgb_control,
    rgb_zone_, brightness_control, per-key-lighting, fn-swap, reprogrammable-keys, persistent-remappable-keys, divert-keys, disable-keyboard-keys, force-sensing,
    crown-smooth, divert-crown, divert-gkeys, m-key-leds, mr-key-led, multiplatform, change-host, gesture2-gestures, gesture2-divert, gesture2-params, haptic-level,
    haptic-play, adc_power_management]
  _modelId: 000000000A9C
  _sensitive: {hires-scroll-mode: ignore, hires-smooth-invert: ignore, hires-smooth-resolution: ignore}
  _unitId: FFFFFFFF
  equalizer: {0: 0, 1: 0, 2: 0, 3: 0, 4: 0, 5: 0, 6: 0, 7: 0, 8: 0, 9: 0}
  sidetone: 0
- _NAME: MX Creative Dialpad
  _modelId: BC0000000000
  _sensitive: {change-host: true, divert-keys: true}
  _unitId: E70987F3
  change-host: null
  divert-keys: {83: 1, 86: 1, 89: 1, 90: 1}
- _NAME: MX Creative Keypad
  _modelId: C35400000000
  _sensitive: {divert-keys: true}
  _unitId: 2F004300
  brightness_control: 70
  divert-keys: {417: 1, 418: 1}
```
</details>

- Errors or warrnings from Solaar:

**Describe the bug**
Solaar Show crashes.

**To Reproduce**
1) Open the terminal
2) type `solaar show
3) press enter
4) observe crash

**Screenshots**

**Additional context**
I am attempting to configure an MX Creative Console (https://www.logitech.com/en-us/products/keyboards/mx-creative-console.html).  As shown in my config, Solaar can detect both the dialpad and the keypad, however the dialpad shows four buttons (Back, Forward, Button 6, and "Left Scroll As Button 7"), while the keypad only shows two as "undefined:.." with a bunch of characters after.  It looks like this device isn't on the supported devices list, but I was hoping to still be able to use it... This is the root problem that I'm trying to fix, however while attempting to investigate if it was possible to add the missing buttons from the keypad, I attempted the "Solaar Show" command, which seems to be broken (see crash stack output).  `Solaar show` seems to crash even when the key/dialpad are disconnected, so at this point I'm feeling like it's unrelated. 

MX Vertical Mouse seems to still be working fine, and I can configure "back/forward" on the dialpad, as well as the "unknowns" on the keypad to send notifications to the desktop... so... at least that's something... >_>

**Comment by GarThor** [comment]
As a side note, updating to Ubuntu 25 has been a total mistake... I'm really considering blowing away this entire machine, and installing mint instead... -_-

**Comment by pfps** [comment]
See #3074 

Could you try downloading Solaar from this repository and then running `bin/solaar show` from this repository?   Version 1.1.19 will be going out soon and verification that this bug has been fixed would be helpful.

**Comment by pfps** [comment]
Could you post the exact unknown:... values as they show in the Solaar main window?  It might be possible to determine their official names from this information.  As well, you could try to divert the keys, one by one, see which key stops working, and post the correspondence.  This would allow adding unofficial names for these keys.

**Comment by pfps** [comment]
There are other aspects of the device that might not be easy to support in Solaar, notably how the dial works as described on the Logitech page.

**Comment by pfps** [comment]
If there is something that could be done for the Creative Console then you should consider creating an enhancement request for that.  There is no guarantee that it could be or would be done, of course.

**Comment by GarThor** [comment]
> See [#3074](https://github.com/pwr-Solaar/Solaar/issues/3074)
> 
> Could you try downloading Solaar from this repository and then running `bin/solaar show` from this repository? Version 1.1.19 will be going out soon and verification that this bug has been fixed would be helpful.

./bin/solaar show
rules cannot access modifier keys in Wayland, accessing process only works on GNOME with Solaar Gnome extension installed
solaar version 1.1.19rc1

```
MX Creative Keypad
     Device path  : /dev/hidraw8
     USB id       : 046d:C354
     Codename     : MX
     Kind         : ?
     Protocol     : HID++ 4.5
     Serial number: 
     Model ID:      C35400000000
     Unit ID:       2F004300
                 1: BL2 20.00.B0017
                 0: U1 66.00.B0017
                 3: 
                 2: 72
     Supports 18 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V7     
            Firmware: 1 BL2 20.00.B0017 ABD4
            Firmware: 0 U1 66.00.B0017 C354
            Firmware: 3   
            Firmware: 2  72 
            Unit ID: 2F004300  Model ID: C35400000000  Transport IDs: {'usbid': 'C354'}
         3: DEVICE NAME            {0005} V5     
            Name: MX Creative Keypad
            Kind: None
         4: KEEP ALIVE             {0008} V1     
         5: unknown:0011           {1100} V0     
         6: DFUCONTROL             {00C3} V1     
         7: unknown:1602           {0216} V0     
         8: DEVICE RESET           {1802} V0     
         9: OOBSTATE               {1805} V0     
        10: unknown:1807           {0718} V0    internal, hidden, unknown:000010 
        11: REPROG CONTROLS V4     {1B04} V6     
            Key/Button Diversion (saved): {unknown:01A1:Diverted, unknown:01A2:Diverted}
            Key/Button Diversion        : {unknown:01A1:Diverted, unknown:01A2:Diverted}
        12: unknown:1E00           {001E} V0    hidden 
        13: unknown:1E02           {021E} V0    internal, hidden 
        14: unknown:1EB0           {B01E} V0    internal, hidden, unknown:000010 
        15: BRIGHTNESS CONTROL     {8040} V1     
            Brightness Control (saved): 70
            Brightness Control        : 70
        16: unknown:92E2           {E292} V0    internal, hidden, unknown:000010 
        17: unknown:180B           {0B18} V0    internal, hidden, unknown:000010 
     Has 2 reprogrammable keys:
         0: unknown:01A1              , default: unknown:0000                => Unknown_1a1               
             divertable, pos:0, group:1, group mask:empty
             reporting: ['diverted']
         1: unknown:01A2              , default: unknown:0000                => Unknown_1a2               
             divertable, pos:0, group:1, group mask:empty
             reporting: ['diverted']
     Battery status unavailable.

G432 Gaming Headset
     Device path  : /dev/hidraw5
     USB id       : 046d:0A9C
     Codename     : G432
     Kind         : ?
     Protocol     : HID++ 4.2
     Serial number: 
     Model ID:      000000000A9C
     Unit ID:       FFFFFFFF
                 0: U1  42.00.B0001
     Supports 6 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
solaar: error: Traceback (most recent call last):
  File "/home/garthor/Solaar/lib/solaar/cli/__init__.py", line 217, in run
    m.run(c, args, _find_receiver, _find_device)
    ~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/garthor/Solaar/lib/solaar/cli/show.py", line 336, in run
    _print_device(d)
    ~~~~~~~~~~~~~^^^
  File "/home/garthor/Solaar/lib/solaar/cli/show.py", line 156, in _print_device
    flags = dev.request(0x0000, feature_bytes)
  File "/home/garthor/Solaar/lib/logitech_receiver/device.py", line 530, in request
    return self.low_level.request(
           ~~~~~~~~~~~~~~~~~~~~~~^
        self.handle or (self.receiver.handle if self.receiver else None),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
        protocol=self.protocol,
        ^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/garthor/Solaar/lib/logitech_receiver/base.py", line 575, in request
    raise exceptions.FeatureCallError(
    ...<4 lines>...
    )
logitech_receiver.exceptions.FeatureCallError: {'number': 255, 'request': 13, 'error': 6, 'params': b'\x01\x00'}
```

hmm... looks like it got further, but then still crashed.

> Could you post the exact unknown:... values as they show in the Solaar main window? It might be possible to determine their official names from this information. As well, you could try to divert the keys, one by one, see which key stops working, and post the correspondence. This would allow adding unofficial names for these keys.

<img width="2249" height="1243" alt="Image" src="https://github.com/user-attachments/assets/18773544-9e29-4d9d-8236-baea41b684a7" />

> There are other aspects of the device that might not be easy to support in Solaar, notably how the dial works as described on the Logitech page.

Hmm... I was actually more concerned with not being able to change the button displays on the keypad.

I was able to find this repository during my research yesterday that might help?  https://github.com/Julusian/node-logitech-mx-creative-console/blob/main/README.md -- Not entirely sure though, I haven't looked that deep yet.  It seems to be a library for support, rather than an app to install... so... 🤷

**Comment by GarThor** [comment]
> If there is something that could be done for the Creative Console then you should consider creating an enhancement request for that. There is no guarantee that it could be or would be done, of course.

enhancement request filed: https://github.com/pwr-Solaar/Solaar/issues/3100

**Comment by pfps** [comment]
The crash in `solaar show` above is new.  Please file an issue for that.

**Comment by GarThor** [comment]
> The crash in `solaar show` above is new. Please file an issue for that.

Do I need to post a separate issue?  The title of this one is already `Crash on "Solaar Show"`

**Comment by pfps** [comment]
OK.

Try  PR #3101 which might solve the problem by making Solaar more defensive about this error.  Run `bin/solaar show` and post the output.



To clone and use Solar from its GitHub repository
```
git clone https://github.com/pwr-Solaar/Solaar.git
cd Solaar
```
Run Solaar as bin/solaar from this directory.


To run PR #3101, first clone Solaar if you have not already done so and cd to the clone directory.  The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
```
git fetch origin pull/3101/head:pull_3101
git checkout pull_3101
```
To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
```
git checkout pull_3101
git fetch origin pull/3101/head
git reset --hard FETCH_HEAD
```

**Comment by pfps** [comment]
It looks as if the problem is in the device itself - the request that Solaar made should not have failed.

**Comment by GarThor** [comment]
> OK.
> 
> Try PR [#3101](https://github.com/pwr-Solaar/Solaar/pull/3101) which might solve the problem by making Solaar more defensive about this error. Run `bin/solaar show` and post the output.
> 
> To clone and use Solar from its GitHub repository
> 
> ```
> git clone https://github.com/pwr-Solaar/Solaar.git
> cd Solaar
> ```
> 
> Run Solaar as bin/solaar from this directory.
> 
> To run PR [#3101](https://github.com/pwr-Solaar/Solaar/pull/3101), first clone Solaar if you have not already done so and cd to the clone directory. The first time you download the pull request, fetch it into a new branch and checkout that branch, as in:
> 
> ```
> git fetch origin pull/3101/head:pull_3101
> git checkout pull_3101
> ```
> 
> To download a new version of the pull request, fetch it and then set your pull branch to the new fetch, as in:
> 
> ```
> git checkout pull_3101
> git fetch origin pull/3101/head
> git reset --hard FETCH_HEAD
> ```

That seems to have fixed it! :D

```
> garthor >>> Solaar > master ≡ >>> git fetch origin pull/3101/head:pull_3101
git checkout pull_3101
remote: Enumerating objects: 6, done.
remote: Counting objects: 100% (6/6), done.
remote: Total 6 (delta 5), reused 6 (delta 5), pack-reused 0 (from 0)
Unpacking objects: 100% (6/6), 569 bytes | 113.00 KiB/s, done.
From https://github.com/pwr-Solaar/Solaar
 * [new ref]           refs/pull/3101/head -> pull_3101
Switched to branch 'pull_3101'
> garthor >>> Solaar > pull_3101 ≢ >>> bin/solaar show
rules cannot access modifier keys in Wayland, accessing process only works on GNOME with Solaar Gnome extension installed
solaar version 1.1.19rc1-1-gbaf69163


MX Creative Keypad
     Device path  : /dev/hidraw8
     USB id       : 046d:C354
     Codename     : MX
     Kind         : ?
     Protocol     : HID++ 4.5
     Serial number: 
     Model ID:      C35400000000
     Unit ID:       2F004300
                 1: BL2 20.00.B0017
                 0: U1 66.00.B0017
                 3: 
                 2: 72
     Supports 18 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V7     
            Firmware: 1 BL2 20.00.B0017 ABD4
            Firmware: 0 U1 66.00.B0017 C354
            Firmware: 3   
            Firmware: 2  72 
            Unit ID: 2F004300  Model ID: C35400000000  Transport IDs: {'usbid': 'C354'}
         3: DEVICE NAME            {0005} V5     
            Name: MX Creative Keypad
            Kind: None
         4: KEEP ALIVE             {0008} V1     
         5: unknown:0011           {1100} V0     
         6: DFUCONTROL             {00C3} V1     
         7: unknown:1602           {0216} V0     
         8: DEVICE RESET           {1802} V0     
         9: OOBSTATE               {1805} V0     
        10: unknown:1807           {0718} V0    internal, hidden, unknown:000010 
        11: REPROG CONTROLS V4     {1B04} V6     
            Key/Button Diversion (saved): {unknown:01A1:Diverted, unknown:01A2:Diverted}
            Key/Button Diversion        : {unknown:01A1:Diverted, unknown:01A2:Diverted}
        12: unknown:1E00           {001E} V0    hidden 
        13: unknown:1E02           {021E} V0    internal, hidden 
        14: unknown:1EB0           {B01E} V0    internal, hidden, unknown:000010 
        15: BRIGHTNESS CONTROL     {8040} V1     
            Brightness Control (saved): 70
            Brightness Control        : 70
        16: unknown:92E2           {E292} V0    internal, hidden, unknown:000010 
        17: unknown:180B           {0B18} V0    internal, hidden, unknown:000010 
     Has 2 reprogrammable keys:
         0: unknown:01A1              , default: unknown:0000                => Unknown_1a1               
             divertable, pos:0, group:1, group mask:empty
             reporting: ['diverted']
         1: unknown:01A2              , default: unknown:0000                => Unknown_1a2               
             divertable, pos:0, group:1, group mask:empty
             reporting: ['diverted']
     Battery status unavailable.

G432 Gaming Headset
     Device path  : /dev/hidraw5
     USB id       : 046d:0A9C
     Codename     : G432
     Kind         : ?
     Protocol     : HID++ 4.2
     Serial number: 
     Model ID:      000000000A9C
     Unit ID:       FFFFFFFF
                 0: U1  42.00.B0001
     Supports 6 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} - can't retrieve
         2: DEVICE FW VERSION      {0003} - can't retrieve
         3: DEVICE NAME            {0005} - can't retrieve
         4: EQUALIZER              {8310} - can't retrieve
         5: SIDETONE               {8300} V0     
            Sidetone (saved): 0
            Sidetone        : 0
     Battery status unavailable.

MX Vertical Wireless Mouse
     Device path  : /dev/hidraw6
     USB id       : 046d:B020
     Codename     : MX Vertical
     Kind         : mouse
     Protocol     : HID++ 4.5
     Serial number: 
     Model ID:      B020407BC08A
     Unit ID:       30E43C76
                 1: BOT 78.00.B0009
                 0: MPM 16.00.B0009
                 3: 
     Supports 30 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V2     
            Firmware: 1 BOT 78.00.B0009 AAE28E5B17FF
            Firmware: 0 MPM 16.00.B0009 B0208E5B17FF
            Firmware: 3   
            Unit ID: 30E43C76  Model ID: B020407BC08A  Transport IDs: {'btleid': 'B020', 'wpid': '407B', 'usbid': 'C08A'}
         3: DEVICE NAME            {0005} V0     
            Name: MX Vertical Advanced Ergonomic Mouse
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
            Configuration: 11000000000000000000000000000000
         6: CRYPTO ID              {0021} V1     
         7: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: MX Vertical
         8: BATTERY STATUS         {1000} V1     
            Battery: 90%, BatteryStatus.DISCHARGING, next level 50%.
         9: unknown:1002           {0210} V0     
        10: REPROG CONTROLS V4     {1B04} V4     
            Key/Button Actions (saved): {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, DPI Switch:Dpi Switch}
            Key/Button Actions        : {Left Button:Left Click, Right Button:Right Click, Middle Button:Mouse Middle Button, Back Button:Mouse Back Button, Forward Button:Mouse Forward Button, DPI Switch:Dpi Switch}
            Key/Button Diversion (saved): {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, DPI Switch:Mouse Gestures}
            Key/Button Diversion        : {Middle Button:Regular, Back Button:Regular, Forward Button:Regular, DPI Switch:Diverted}
        11: PERSISTENT REMAPPABLE ACTION {1C00} V0     
            Persistent Key/Button Mapping        : {unknown:0000:No Output (only as default), Left Button:Mouse Button Left, Right Button:Mouse Button Right, Middle Button:Mouse Button Middle, Back Button:Mouse Button Back, Forward Button:Mouse Button Forward}
        12: CHANGE HOST            {1814} V1     
            Change Host        : 1:Ailita-2
        13: HOSTS INFO             {1815} V1     
            Host 0 (unpaired): Ailita-2
            Host 1 (unpaired): AILITA-MK2
            Host 2 (unpaired): <redacted>
        14: XY STATS               {2250} V0     
        15: unknown:18B1           {B118} V0    internal, hidden 
        16: VERTICAL SCROLLING     {2100} V0     
            Roller type: standard
            Ratchet per turn: 24
            Scroll lines: 0
        17: LOWRES WHEEL           {2130} V0     
            Wheel Reports: HID
            Scroll Wheel Diversion (saved): False
            Scroll Wheel Diversion        : False
        18: ADJUSTABLE DPI         {2201} V1     
            Sensitivity (DPI) (saved): 3600
            Sensitivity (DPI)        : 3600
        19: unknown:1803           {0318} V0    internal, hidden 
        20: CONFIG DEVICE PROPS    {1806} V5     
        21: unknown:1813           {1318} V0    internal, hidden 
        22: OOBSTATE               {1805} V0     
        23: unknown:1830           {3018} V0    internal, hidden 
        24: unknown:18A1           {A118} V0    internal, hidden 
        25: unknown:1E00           {001E} V0    hidden 
        26: unknown:1EB0           {B01E} V0    internal, hidden 
        27: unknown:1E22           {221E} V0    internal, hidden 
        28: unknown:1861           {6118} V0    internal, hidden 
        29: unknown:18C0           {C018} V0    internal, hidden 
     Has 7 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             analytics_key_events, reprogrammable, mse, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             analytics_key_events, reprogrammable, mse, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             analytics_key_events, raw_xy, persistently_divertable, divertable, reprogrammable, mse, pos:0, group:2, group mask:g1,g2
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             analytics_key_events, raw_xy, persistently_divertable, divertable, reprogrammable, mse, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             analytics_key_events, raw_xy, persistently_divertable, divertable, reprogrammable, mse, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: DPI Switch                , default: Dpi Switch                  => Dpi Switch                
             analytics_key_events, raw_xy, persistently_divertable, divertable, reprogrammable, mse, pos:0, group:2, group mask:g1,g2
             reporting: ['raw_xy_diverted', 'diverted']
         6: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             force_raw_xy, raw_xy, virtual, divertable, pos:0, group:3, group mask:empty
             reporting: default
     Has 6 persistent remappable keys:
         0: Left Button                => Mouse Button: Mouse Button Left
         1: Right Button               => Mouse Button: Mouse Button Right
         2: Middle Button              => Mouse Button: Mouse Button Middle
         3: Back Button                => Mouse Button: Mouse Button Back
         4: Forward Button             => Mouse Button: Mouse Button Forward
         5: unknown:0000               => None
     Battery: 90%, BatteryStatus.DISCHARGING, next level 50%.

MX Creative Dialpad
     Device path  : /dev/hidraw7
     USB id       : 046d:BC00
     Codename     : MX Dialpad
     Kind         : ?
     Protocol     : HID++ 4.5
     Serial number: 
     Model ID:      BC0000000000
     Unit ID:       E70987F3
                 1: BL2 18.00.B0016
                 0: RBO 07.00.B0016
                 3: 
                 2: 72
     Supports 30 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} V0     
         2: DEVICE FW VERSION      {0003} V7     
            Firmware: 1 BL2 18.00.B0016 BC00C5A99DF6
            Firmware: 0 RBO 07.00.B0016 BC00C5A99DF6
            Firmware: 3   
            Firmware: 2  72 
            Unit ID: E70987F3  Model ID: BC0000000000  Transport IDs: {'btleid': 'BC00'}
         3: DEVICE NAME            {0005} V4     
            Name: MX Creative Dialpad
            Kind: None
         4: WIRELESS DEVICE STATUS {1D4B} V0     
         5: CONFIG CHANGE          {0020} V0     
            Configuration: 11000000000000000000000000000000
         6: CRYPTO ID              {0021} V1     
         7: DEVICE FRIENDLY NAME   {0007} V0     
            Friendly Name: MX Dialpad
         8: unknown:0011           {1100} V0     
         9: UNIFIED BATTERY        {1004} V5     
            Battery: 100%, BatteryStatus.DISCHARGING.
        10: REPROG CONTROLS V4     {1B04} V6     
            Key/Button Diversion (saved): {Back Button:Diverted, Forward Button:Diverted, Button 6:Diverted, Left Scroll As Button 7:Diverted}
            Key/Button Diversion        : {Back Button:Diverted, Forward Button:Diverted, Button 6:Diverted, Left Scroll As Button 7:Diverted}
        11: CHANGE HOST            {1814} V1     
            Change Host        : 1:Ailita-2
        12: HOSTS INFO             {1815} V2     
            Host 0 (paired): Ailita-2
            Host 1 (unpaired): 
            Host 2 (unpaired): 
        13: unknown:4610           {1046} V0     
        14: DFUCONTROL             {00C3} V1     
        15: DEVICE RESET           {1802} V0     
        16: unknown:1803           {0318} V0    internal, hidden, unknown:000010 
        17: unknown:1807           {0718} V0    internal, hidden, unknown:000010 
        18: unknown:1816           {1618} V0    internal, hidden, unknown:000010 
        19: OOBSTATE               {1805} V0     
        20: unknown:1830           {3018} V0    internal, hidden, unknown:000010 
        21: unknown:1891           {9118} V0    internal, hidden, unknown:000008 
        22: unknown:18A1           {A118} V0    internal, hidden, unknown:000010 
        23: unknown:1E00           {001E} V0    hidden 
        24: unknown:1E02           {021E} V0    internal, hidden 
        25: unknown:1602           {0216} V0     
        26: unknown:1EB0           {B01E} V0    internal, hidden, unknown:000010 
        27: unknown:1861           {6118} V0    internal, hidden, unknown:000010 
        28: unknown:18B1           {B118} V0    internal, hidden, unknown:000010 
        29: unknown:9205           {0592} V0    internal, hidden, unknown:000010 
     Has 4 reprogrammable keys:
         0: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             analytics_key_events, divertable, reprogrammable, mse, pos:0, group:1, group mask:g1
             reporting: ['diverted']
         1: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             analytics_key_events, divertable, reprogrammable, mse, pos:0, group:1, group mask:g1
             reporting: ['diverted']
         2: Button 6                  , default: unknown:0109                => Unknown_59                
             analytics_key_events, divertable, reprogrammable, mse, pos:0, group:1, group mask:g1
             reporting: ['diverted']
         3: Left Scroll As Button 7   , default: unknown:0109                => Unknown_5a                
             analytics_key_events, divertable, reprogrammable, mse, pos:0, group:1, group mask:g1
             reporting: ['diverted']
     Battery: 100%, BatteryStatus.DISCHARGING.
```

**Comment by GarThor** [comment]
> It looks as if the problem is in the device itself - the request that Solaar made should not have failed.

I'm wondering which device was killing it?  I don't see a device name in the crash output/callstack so...

**Comment by pfps** [comment]
It's the headset.  That was what was being shown and that is what is now producing the can't retrieve messages.

It might be that the headset is one of those devices where part of the firmware is in the receiver and part in the device.  So if the device is inactive things go weird.  Can you try `bin/solaar show` when you know that the headset is active?

**Comment by GarThor** [comment]
Hmm... curious... 

TBH, it's not _actually_ a headset.  It's the USB adapter for a headset, plugged into my KVM switch... The headset itself died _years_ ago, but the usb adapter keeps on chugging.  Currently, the only thing plugged into it is one of those microphones that's supposed to be plugged into a headset, because it has better audio recording and filtering properties than the one on my webcam.  I use a bluetooth (non logitech) headphones for everything else...

Here's the output of just the "headset"
```
G432 Gaming Headset
     Device path  : /dev/hidraw5
     USB id       : 046d:0A9C
     Codename     : G432
     Kind         : ?
     Protocol     : HID++ 4.2
     Serial number: 
     Model ID:      000000000A9C
     Unit ID:       FFFFFFFF
                 0: U1  42.00.B0001
     Supports 6 HID++ 2.0 features:
         0: ROOT                   {0000} V0     
         1: FEATURE SET            {0001} - can't retrieve
         2: DEVICE FW VERSION      {0003} - can't retrieve
         3: DEVICE NAME            {0005} - can't retrieve
         4: EQUALIZER              {8310} - can't retrieve
         5: SIDETONE               {8300} V0     
            Sidetone (saved): 0
            Sidetone        : 0
     Battery status unavailable.
```

Afaik, there's nothing to "activate"?  It's just a USB 2.0 <--> 3.5mm adapter (with 3 channels)... >_>

I'd just plug the mic directly into the KVM, but the KVM doesn't have a 3-channel 3.5mm jack... so I'd still need an adapter to go from 2 ports to 1 jack.

One other interesting tidbit: The creative keypad doesn't actually even show up when it's plugged into the KVM.  I normally have this problem with gaming controllers... kindof annoying that one is bluetooth (with a button to switch between devicves), and the other one is USB -- but doesn't work through a KVM?

**Comment by pfps** [comment]
OK
