### ISSUE TITLE
MX Keys buttons not useful

### ISSUE THREAD

**Issue by kabeersvohra** [pwr-Solaar/Solaar#979]
**Information**
- Solaar version - `solaar 1.0.4rc1`
- Distribution: `Ubuntu 20.04 LTS`
- Kernel version (ex. `uname -srmo`): `Linux 5.4.0-51-generic x86_64 GNU/Linux`
- Output of `solaar show`:
```
Unifying Receiver
  Device path  : /dev/hidraw4
  USB id       : 046d:C52B
  Serial       : 590B9606
    Firmware   : 24.10.B0036
    Bootloader : 00.06
  Has 2 paired device(s) out of a maximum of 6.
  Notifications: wireless, software present (0x000900)
  Device activity counters: 1=187, 2=139

  1: MX Keys Keyboard
     Device path  : /dev/hidraw9
     WPID         : 408A
     Codename     : MK Keys
     Kind         : keyboard
     Protocol     : HID++ 4.5
     Polling rate : 20 ms (50Hz)
     Serial number: FB164CD8
     Model ID:      B35B408A0000
     Unit ID:       FB164CD8
        Bootloader: BL1 08.00.B0011
          Firmware: MPK 12.00.B0011
             Other: 
     The power switch is located on the edge of top right corner.
     Supports 33 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BL1 08.00.B0011 00008169E8BB
            Firmware: Firmware MPK 12.00.B0011 408A8169E8BB
            Firmware: Other   
            Unit ID: FB164CD8  Model ID: B35B408A0000  Transport IDs: {'btleid': 'B35B', 'wpid': '408A'}
         3: DEVICE NAME            {0005}   
            Name: MX Keys Wireless Keyboard
            Kind: keyboard
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: DEVICE FRIENDLY NAME   {0007}   
         7: BATTERY STATUS         {1000}   
            Battery: 50%, discharging, next level 20%.
         8: REPROG CONTROLS V4     {1B04}   
         9: CHANGE HOST            {1814}   
            Change Host: 1:pc
        10: HOSTS INFO             {1815}   
            Host 0 (paired): 
            Host 1 (unpaired): 
            Host 2 (unpaired): 
        11: BACKLIGHT2             {1982}   
            Backlight: True
        12: K375S FN INVERSION     {40A3}   
            Swap Fx function: False
        13: ENCRYPTION             {4100}   
        14: LOCK KEY STATE         {4220}   
        15: KEYBOARD DISABLE KEYS  {4521}   
            Disable keys: {'1': False, '2': False, '4': False, '8': False, '16': False}
        16: MULTIPLATFORM          {4531}   
            Set OS: Windows
        17: DFUCONTROL SIGNED      {00C2}   
        18: DEVICE RESET           {1802}   internal, hidden
        19: unknown:1803           {1803}   internal, hidden
        20: CONFIG DEVICE PROPS    {1806}   internal, hidden
        21: unknown:1813           {1813}   internal, hidden
        22: OOBSTATE               {1805}   internal, hidden
        23: unknown:1830           {1830}   internal, hidden
        24: unknown:1890           {1890}   internal, hidden
        25: unknown:1891           {1891}   internal, hidden
        26: unknown:18A1           {18A1}   internal, hidden
        27: unknown:1DF3           {1DF3}   internal, hidden
        28: unknown:1E00           {1E00}   hidden
        29: unknown:1EB0           {1EB0}   internal, hidden
        30: unknown:1861           {1861}   internal, hidden
        31: unknown:1A20           {1A20}   internal, hidden
        32: unknown:18B0           {18B0}   internal, hidden
     Has 24 reprogrammable keys:
         0: Host Switch channel 1     , default: HostSwitch Channel 1        => HostSwitch Channel 1      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         1: Host Switch channel 2     , default: HostSwitch Channel 2        => HostSwitch Channel 2      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         2: Host Switch channel 3     , default: HostSwitch Channel 3        => HostSwitch Channel 3      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
         3: Brightness Down           , default: Brightness Down             => Brightness Down           
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:1, group:0, group mask:empty
             reporting: default
         4: Brightness Up             , default: Brightness Up               => Brightness Up             
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:2, group:0, group mask:empty
             reporting: default
         5: Mission Control/Task View , default: Mission Control/Task View   => Mission Control/Task View 
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:3, group:0, group mask:empty
             reporting: default
         6: Dashboard Launchpad/Action Center, default: Dashboard Launchpad/Action Center => Dashboard Launchpad/Action Center
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:4, group:0, group mask:empty
             reporting: default
         7: Show Desktop              , default: Show Desktop                => Show Desktop              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:5, group:0, group mask:empty
             reporting: default
         8: Backlight Down            , default: Backlight Down              => Backlight Down            
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:6, group:0, group mask:empty
             reporting: default
         9: Backlight Up              , default: Backlight Up                => Backlight Up              
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:7, group:0, group mask:empty
             reporting: default
        10: Previous Fn               , default: Previous                    => Previous                  
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:8, group:0, group mask:empty
             reporting: default
        11: Play/Pause Fn             , default: Play/Pause                  => Play/Pause                
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:9, group:0, group mask:empty
             reporting: default
        12: Next Fn                   , default: Next                        => Next                      
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:10, group:0, group mask:empty
             reporting: default
        13: Mute Fn                   , default: Mute                        => Mute                      
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:11, group:0, group mask:empty
             reporting: default
        14: Volume Down Fn            , default: Volume Down                 => Volume Down               
             is FN, FN sensitive, reprogrammable, divertable, persistently divertable, analytics key events, pos:12, group:0, group mask:empty
             reporting: default
        15: Volume Up Fn              , default: Volume Up                   => Volume Up                 
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        16: Calculator                , default: Calculator                  => Calculator                
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        17: Screen Capture/Print Screen, default: Screen Capture              => Screen Capture            
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        18: App Contextual Menu/Right Click, default: Right Click/App Contextual Menu => Right Click/App Contextual Menu
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        19: Lock PC                   , default: WindowsLock                 => WindowsLock               
             nonstandard, reprogrammable, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        20: Left Arrow                , default: Keyboard Left Arrow         => Keyboard Left Arrow       
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        21: Right Arrow               , default: Keyboard Right Arrow        => Keyboard Right Arrow      
             nonstandard, divertable, persistently divertable, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        22: F Lock                    , default: Do Nothing One              => Do Nothing One            
             is FN, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
        23: unknown:0034              , default: Do Nothing One              => Do Nothing One            
             nonstandard, analytics key events, pos:0, group:0, group mask:empty
             reporting: default
     Battery: 50%, discharging, next level 20%.

  2: Wireless Mouse MX Master
     Device path  : /dev/hidraw10
     WPID         : 4071
     Codename     : MX Master
     Kind         : mouse
     Protocol     : HID++ 4.5
     Polling rate : 8 ms (125Hz)
     Serial number: 0A0B52B1
     Model ID:      B01E40710000
     Unit ID:       27363817
        Bootloader: BOT 56.10.B0005
          Firmware: MPM 12.10.B0005
          Firmware: MPM 12.10.B0005
             Other: 
     The power switch is located on the base.
     Supports 32 HID++ 2.0 features:
         0: ROOT                   {0000}   
         1: FEATURE SET            {0001}   
         2: DEVICE FW VERSION      {0003}   
            Firmware: Bootloader BOT 56.10.B0005 40717622661101
            Firmware: Firmware MPM 12.10.B0005 B01E7622661101
            Firmware: Firmware MPM 12.10.B0005 40717622661101
            Firmware: Other   
            Unit ID: 27363817  Model ID: B01E40710000  Transport IDs: {'btleid': 'B01E', 'wpid': '4071'}
         3: DEVICE NAME            {0005}   
            Name: Wireless Mouse MX Master
            Kind: mouse
         4: WIRELESS DEVICE STATUS {1D4B}   
         5: RESET                  {0020}   
         6: CRYPTO ID              {0021}   
         7: BATTERY STATUS         {1000}   
            Battery: 90%, discharging, next level 50%.
         8: CONFIG DEVICE PROPS    {1806}   internal, hidden
         9: CHANGE HOST            {1814}   
            Change Host: 1:pc
        10: REPROG CONTROLS V4     {1B04}   
            Key/Button Actions: {'80': 80, '81': 81, '82': 82, '83': 83, '86': 86, '195': 195, '196': 196}
        11: ADJUSTABLE DPI         {2201}   
            Sensitivity (DPI): 1000
        12: VERTICAL SCROLLING     {2100}   
            Roller type: 3G
            Ratchet per turn: 24
            Scroll lines: 0
        13: SMART SHIFT            {2110}   
            Scroll Wheel Rachet: 16
        14: HIRES WHEEL            {2121}   
            Multiplier: 8
            Has invert: Normal wheel motion
            Has ratchet switch: Normal wheel mode
            High resolution mode
            HID notification
            Scroll Wheel Direction: False
            Scroll Wheel Resolution: True
        15: GESTURE 2              {6501}   
            Gestures: {'46': True, '45': True}
        16: DFUCONTROL SIGNED      {00C2}   
        17: unknown:1813           {1813}   internal, hidden
        18: unknown:1830           {1830}   internal, hidden
        19: unknown:1890           {1890}   internal, hidden
        20: unknown:1891           {1891}   internal, hidden
        21: unknown:18A1           {18A1}   internal, hidden
        22: unknown:18C0           {18C0}   internal, hidden
        23: unknown:1DF3           {1DF3}   internal, hidden
        24: unknown:1E00           {1E00}   hidden
        25: unknown:1EB0           {1EB0}   internal, hidden
        26: unknown:1803           {1803}   internal, hidden
        27: unknown:1861           {1861}   internal, hidden
        28: unknown:9001           {9001}   internal, hidden
        29: unknown:9200           {9200}   internal, hidden
        30: unknown:9202           {9202}   internal, hidden
        31: OOBSTATE               {1805}   internal, hidden
     Has 8 reprogrammable keys:
         0: Left Button               , default: Left Click                  => Left Click                
             mse, pos:0, group:1, group mask:g1
             reporting: default
         1: Right Button              , default: Right Click                 => Right Click               
             mse, pos:0, group:1, group mask:g1
             reporting: default
         2: Middle Button             , default: Mouse Middle Button         => Mouse Middle Button       
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         3: Back Button               , default: Mouse Back Button           => Mouse Back Button         
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         4: Forward Button            , default: Mouse Forward Button        => Mouse Forward Button      
             mse, reprogrammable, divertable, raw XY, pos:0, group:2, group mask:g1,g2
             reporting: default
         5: App Switch Gesture        , default: Gesture Button Navigation   => Gesture Button Navigation 
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         6: Smart Shift               , default: Smart Shift                 => Smart Shift               
             mse, reprogrammable, divertable, raw XY, pos:0, group:3, group mask:g1,g2,g3
             reporting: default
         7: Virtual Gesture Button    , default: Virtual Gesture Button      => Virtual Gesture Button    
             divertable, virtual, raw XY, force raw XY, pos:0, group:4, group mask:empty
             reporting: default
     Has 2 gesture(s), 0 param(s) and 4 spec(s):
        Thumbwheel                 Enabled (   0): True
        NaturalScrolling           Enabled (   1): True
        period unit                Spec    (   3): 800
        DVI field width            Spec    (   1): 8
        field widths               Spec    (   2): 8
        resolution                 Spec    (   4): 2048
     Battery: 90%, discharging, next level 50%.
```

**Describe the bug**
When using the MX Keys special keys, a lot of them do not work:
    F1 (brightness down) sends nothing
    F2 (brightness up) sends nothing
    F3 (unaligned blocks) sends super+tab
    F4 (aligned blocks) sends super+a
    F5 (screen with arrow) sends super+d
    The rest of the F-buttons work as expected
    Lock (above number pad) sends super+l

Would it be possible to make these buttons customisable in some way so that we could use these keys to perform the commands that we want?

Thanks a lot

**Comment by pfps** [comment]
From the information you provided, the brightness keys are sending keycodes that are their usual behaviour.  Something is consuming them but not changing screen brightness (or maybe there is no way to change screen brightness on your machine).

There is no way to program your keyboard to change the keycodes keys produce.  In Linux you can change how keycodes are changed into input characters using several mechanisms, but they all require understanding how Linux and X11 do keyboard input.  Most window managers allow you to perform special actions in response to certain input characters.  This shortcut mechanism might be able to do what you want.

There is a way to program your keyboard to produce special messages from some of its keys (the reprogrammable keys) but Linux ignores the messages.

**Comment by barolo** [comment]
This seems to be desktop environment dependant? I have the same keys and almost identical keyboard [ Craft ] and thy all work under KDE/Plasma

**Comment by pfps** [comment]
@barolo Do you have your monitor brightness keys working?  Do you know what character(s) they turn into?  If they are working, do you know what is processing their output?

**Comment by kabeersvohra** [comment]
@pfps Cheers for the really quick reply. When I run `xev` and press the brightness buttons (F1, F2) I do not get any output, it seems I have the same experience as this user on Reddit - https://www.reddit.com/r/linuxhardware/comments/g34lgo/logitech_mx_keys_on_linux/fvwqd67/?utm_source=reddit&utm_medium=web2x&context=3.

@barolo Do the brightness keys work for you also? I am surprised as nothing is detected for me.

**Comment by pfps** [comment]
It certainly seems as if these two buttons do not produce any output.  I even tried to see what they were doing using WireShark, which didn't see any USB  or BT activity.

**Comment by barolo** [comment]
My mistake, I had conflated my macOS usage with my Linux usage, it works under macOS onbiously, under Linux it doesn't. Do you want me to sniff it out under Windows?

**Comment by pfps** [comment]
@barolo I expect that you will find that the Logitech driver puts these keys in "diversion" mode (so that they send HID++ messages) and then does the brightness changing itself.  But verifying this guess would be useful.

**Comment by pfps** [comment]
I found out at least part of what is happening.

These keys are sensitive to the current OS setting, and in WIndows they do nothing.  You can change their behaviour in Solaar by using the Set OS setting, but this also changes how a few other keys work

**Comment by pfps** [comment]
If you are interested in having these keys work without switching to the MacOS layout you should try PR #988, which allows you to divert keyboard keys to HID++ messages and then processes these messages to produce X11 keypresses.  For more information look in PR #988

**Comment by kabeersvohra** [comment]
Thank you very much @pfps I will give this a shot. Just tried out now with the MacOS keyboard layout and can confirm that the keys are working however I do not want to use the MacOS layout for obvious reasons.

**Comment by pfps** [comment]
For each key you have to set each key you want handled to Divert in the Key/Button Diversion setting.  Then there has to be a rule to turn the diverted message into a keypress.  I only have this set up for Brightness Down and Up.  Let me know that you think the other keys should do.

**Comment by kabeersvohra** [comment]
I think for the other keys, it is probably ideal for people to divert them themselves because for example with my Regolith Linux, I lock using Super+Esc but not many do it like this. Also the other keys don't have a standard use for me with a tiling WM but would be nice to divert them to uses that I like. I haven't had a chance yet to try out the version in the PR you linked but I will do this soon and get back to you with my success. Thanks for the help :+1:

**Comment by pfps** [comment]
The system is set up to allow user-defined rules to override built-in rules, so having a default for the keys that are useless seems like a good idea.

**Comment by pfps** [comment]
PR #988 has the facilities to modify how all these keys work.  

The problem with F3 and F4 is that they don't do anything when the keyboard is set to Windows state.  WIth PR #988 you can set these keys to use HID++ notifications and then process the notifications to do something useful.  Currently PR #988 has rules to simulate X11 brightness keys for these two keys so all you have to do is to divert them using Solaar.  Solaar does have to be running so that the HID++ notifications are processed.

The other keys do send something so you can use your display manager to perform some action in response to what these keys do.  For example you could have Super+L run a lock screen program.  You could also write rules (in ~/.config/solaar/divert.yaml) to execute a program in response to the HID++ notifications and divert the keys to HID++.

PR #988 is still not in its final form, but should be good enough to use.

**Comment by pfps** [comment]
Fixed by #988

**Comment by kabeervohra** [comment]
> Fixed by #988

By the way, I have (a year later) tested this by diverting the brightness up/down buttons using the latest version of solaar and it works! Thank you

**Comment by kabeervohra** [comment]
So I have run into another issue with it, not sure if this is related to solaar or not. When I did the remapping in solaar, pressing the buttons did activate the brightness UI on the screen but does not actually change the brightness for me. Therefore I did these two mappings in i3

```
bindsym XF86MonBrightnessDown exec brightness -5
bindsym XF86MonBrightnessUp exec brightness +5
```

However for some reason the `XF86MonBrightnessDown` mapping does not work and the `XF86MonBrightnessUp` mapping does work, would this be due to the different keypresses that solaar emits? Thank you

**Comment by kabeervohra** [comment]
I created my own shell script which works called `brightness`, I still get the UI when pressing the brightness down button suggesting that the mapping does not work for that key, however the brightness up button does execute my script successfully

**Comment by pfps** [comment]
I have a Craft keyboard, which I think has the same keyboard layout and behaviour.   The brightness keys do nothing without some intervention by Solaar. What I do is divert both keys.  Then in recent versions of Solaar (1.0.6 at least) there is a rule that converts the diverted keys to XF86... keypresses.  This only works under X11, not Wayland.  I then have Power Manager handle the display brightness keys.

What UI do you see when you press the brightness down key?  Solaar?  There should be no reason for the Solaar main window to pop up when you press a key.
